[project]
name = "rag-mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.17",
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.0",
    "sentence-transformers>=5.1.0",
]
